services:
  db:
    image: postgres:latest
    container_name: ${DB_CONTAINER_NAME}
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_EXT_PORT}:${DB_INT_PORT}"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
